### ISSUE TITLE
[cbor] Unable to roundtrip map[string]*CustomStruct

### ISSUE THREAD

**Issue by dignifiedquire** [polydawn/refmt#22]
This might be a bug in the library or a user error, I am not a 100% certain. 

When using `atlas.BuildEntry(CustomStruct{}).StructMap().Autogenerate()` with a struct like this

```go
type CustomStruct{
  Hello int
}
```

And I try roundtrip the following structure
```go
list := map[string]*CustomStruct{
  "hello": &CustomStruct{Hello: 1},
  "world" &CustomStruct{Hello: 9},
}
```
I get back

```go
map[string]*CustomStruct{
  "hello": &CustomStruct{Hello: 9},
  "world" &CustomStruct{Hello: 9},
}
```

When I check the raw bytes, it gets serialized correctly, but on the output it seems the values are overwriting each other somehow.

**Comment by whyrusleeping** [comment]
This appears to have been fixed by the latest commit, 21 days ago

**Comment by dignifiedquire** [comment]
yep, outdated versions are not your friends
